frontend:
  - changed-files:
      - any-glob-to-any-file: "frontend/src/**/*"
backend:
  - changed-files:
      - any-glob-to-any-file: "backend/**/*"
github-actions:
  - changed-files:
      - any-glob-to-any-file: ".github/**/*"
docs:
  - changed-files:
      - any-glob-to-any-file:
          - "README.md"
          - "docs/**/*"
