version: "3"

services:
  task_canvas_web:
    build:
      context: ./frontend
    ports:
      - "${NEXT_PORT}:3000"
    env_file:
      - .env.test
    volumes:
      - type: bind
        source: ./frontend
        target: /task-canvas/frontend
    networks:
      - task_canvas_network

networks:
  task_canvas_network:
    driver: bridge
