version: "3"

services:
  task_canvas_web:
    build:
      context: ./frontend
    ports:
      - "${NEXT_PORT}:3000"
    depends_on:
      - task_canvas_api
    env_file:
      - .env

  task_canvas_api:
    build:
      context: ./backend
    volumes:
      - ./backend:/go/src/app/backend
    ports:
      - "${GO_PORT}:8080"
    depends_on:
      - task_canvas_db
    env_file:
      - .env

  task_canvas_db:
    image: postgres:latest
    container_name: ${POSTGRES_HOST}
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./backend/app/database/init:/docker-entrypoint-initdb.d
