version: "3"

services:
  task_canvas_web:
    build:
      context: ./frontend
    ports:
      - "${NEXT_PORT}:3000"
    depends_on:
      - task_canvas_api
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./frontend
        target: /task-canvas/frontend

  task_canvas_api:
    build:
      context: ./backend
    volumes:
      - ./backend:/backend
    ports:
      - "${GO_PORT}:8080"
    networks:
      - task_canvas_network
    depends_on:
      - task_canvas_db
    env_file:
      - .env

  task_canvas_db:
    image: postgres:latest
    container_name: ${POSTGRES_CONTAINER}
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - task_canvas_network
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./backend/app/database/init:/docker-entrypoint-initdb.d
      - ./backend/app/database/seeds:/backend/app/database/seeds

networks:
  task_canvas_network:
    driver: bridge